// Stub PokiSDK - all external calls removed for offline use
window.PokiSDK = {
	init: function() { return Promise.resolve(); },
	initWithVideoHB: function() { return Promise.resolve(); },
	customEvent: function() {},
	commercialBreak: function() { return Promise.resolve(); },
	rewardedBreak: function() { return Promise.resolve(false); },
	displayAd: function() {},
	destroyAd: function() {},
	getLeaderboard: function() { return Promise.resolve(); },
	getSharableURL: function() { return Promise.resolve(""); },
	getURLParam: function() { return ""; },
	disableProgrammatic: function() {},
	gameLoadingStart: function() {},
	gameLoadingFinished: function() {},
	gameInteractive: function() {},
	roundStart: function() {},
	roundEnd: function() {},
	muteAd: function() {},
	setDebug: function() {},
	gameplayStart: function() {},
	gameplayStop: function() {},
	gameLoadingProgress: function() {},
	happyTime: function() {},
	setPlayerAge: function() {},
	togglePlayerAdvertisingConsent: function() {},
	logError: function() {},
	sendHighscore: function() {},
	setDebugTouchOverlayController: function() {}
};
